# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "geerlingguy/centos7"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  #config.vm.network "public_network", use_dhcp_assigned_default_route: true
  config.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh", auto_correct: true
end
